#logging:
#  level:
#    org.springframework.security: debug

spring:
  servlet:
    multipart:
      max-file-size: 10MB
  datasource:
    url: jdbc:postgresql://localhost:5432/geochat?serverTimezone=UTC&useSSL=false
    username: postgres
    password: root
  jpa:
      hibernate:
        ddl-auto: update
      properties:
        hibernate:
          dialect: org.hibernate.dialect.PostgreSQLDialect
          temp.use_jdbc_metadata_defaults: false
  security:
    oauth2:
      client:
        registration:
          google:
            clientId: 382110776474-m3lvhvfbmsvv2kln5i81nkqi8tb6ng8s.apps.googleusercontent.com
            clientSecret: 494RQriQ9LxR-jBvQQZ0u3CQ
            redirectUri: http://localhost:4200/oauth2/callback/google
            scope:
              - email
              - profile
          vk:
            clientId: 7729199
            clientSecret: E7Aj6odkTGEmtWG6XDkE
            redirectUri: http://localhost:4200/oauth2/callback/vk
            provider: vk
            clientName: vk
            client-authentication-method: post
            authorization-grant-type: authorization_code
            scope:
              - email
              - photos
        provider:
          vk:
            authorization-uri: https://oauth.vk.com/authorize
            token-uri: https://oauth.vk.com/access_token
            user-info-uri: https://api.vk.com/method/users.get
#            user-name-attribute:
